// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: datastore.proto

package datastore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Datastore service

type DatastoreService interface {
	Recipe(ctx context.Context, in *DatastoreRequest, opts ...client.CallOption) (*DatastoreResponse, error)
}

type datastoreService struct {
	c    client.Client
	name string
}

func NewDatastoreService(name string, c client.Client) DatastoreService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "datastore"
	}
	return &datastoreService{
		c:    c,
		name: name,
	}
}

func (c *datastoreService) Recipe(ctx context.Context, in *DatastoreRequest, opts ...client.CallOption) (*DatastoreResponse, error) {
	req := c.c.NewRequest(c.name, "Datastore.Recipe", in)
	out := new(DatastoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Datastore service

type DatastoreHandler interface {
	Recipe(context.Context, *DatastoreRequest, *DatastoreResponse) error
}

func RegisterDatastoreHandler(s server.Server, hdlr DatastoreHandler, opts ...server.HandlerOption) error {
	type datastore interface {
		Recipe(ctx context.Context, in *DatastoreRequest, out *DatastoreResponse) error
	}
	type Datastore struct {
		datastore
	}
	h := &datastoreHandler{hdlr}
	return s.Handle(s.NewHandler(&Datastore{h}, opts...))
}

type datastoreHandler struct {
	DatastoreHandler
}

func (h *datastoreHandler) Recipe(ctx context.Context, in *DatastoreRequest, out *DatastoreResponse) error {
	return h.DatastoreHandler.Recipe(ctx, in, out)
}
