// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datastore.proto

package datastore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatastoreRequest struct {
	RequestJSON          string   `protobuf:"bytes,1,opt,name=requestJSON,proto3" json:"requestJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatastoreRequest) Reset()         { *m = DatastoreRequest{} }
func (m *DatastoreRequest) String() string { return proto.CompactTextString(m) }
func (*DatastoreRequest) ProtoMessage()    {}
func (*DatastoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d08157cfd31fc929, []int{0}
}

func (m *DatastoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatastoreRequest.Unmarshal(m, b)
}
func (m *DatastoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatastoreRequest.Marshal(b, m, deterministic)
}
func (m *DatastoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatastoreRequest.Merge(m, src)
}
func (m *DatastoreRequest) XXX_Size() int {
	return xxx_messageInfo_DatastoreRequest.Size(m)
}
func (m *DatastoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatastoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatastoreRequest proto.InternalMessageInfo

func (m *DatastoreRequest) GetRequestJSON() string {
	if m != nil {
		return m.RequestJSON
	}
	return ""
}

type DatastoreResponse struct {
	ResponseJSON         string   `protobuf:"bytes,1,opt,name=responseJSON,proto3" json:"responseJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatastoreResponse) Reset()         { *m = DatastoreResponse{} }
func (m *DatastoreResponse) String() string { return proto.CompactTextString(m) }
func (*DatastoreResponse) ProtoMessage()    {}
func (*DatastoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d08157cfd31fc929, []int{1}
}

func (m *DatastoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatastoreResponse.Unmarshal(m, b)
}
func (m *DatastoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatastoreResponse.Marshal(b, m, deterministic)
}
func (m *DatastoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatastoreResponse.Merge(m, src)
}
func (m *DatastoreResponse) XXX_Size() int {
	return xxx_messageInfo_DatastoreResponse.Size(m)
}
func (m *DatastoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatastoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatastoreResponse proto.InternalMessageInfo

func (m *DatastoreResponse) GetResponseJSON() string {
	if m != nil {
		return m.ResponseJSON
	}
	return ""
}

func init() {
	proto.RegisterType((*DatastoreRequest)(nil), "DatastoreRequest")
	proto.RegisterType((*DatastoreResponse)(nil), "DatastoreResponse")
}

func init() { proto.RegisterFile("datastore.proto", fileDescriptor_d08157cfd31fc929) }

var fileDescriptor_d08157cfd31fc929 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x49, 0x2c, 0x49,
	0x2c, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe1, 0x12, 0x70,
	0x81, 0x09, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x29, 0x70, 0x71, 0x17, 0x41, 0x98,
	0x5e, 0xc1, 0xfe, 0x7e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xc8, 0x42, 0x4a, 0xe6, 0x5c,
	0x82, 0x48, 0xba, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x94, 0xb8, 0x78, 0x8a, 0xa0, 0x6c,
	0x24, 0x7d, 0x28, 0x62, 0x46, 0x76, 0x5c, 0x9c, 0x70, 0x8d, 0x42, 0x86, 0x5c, 0x6c, 0x41, 0xa9,
	0xc9, 0x99, 0x05, 0xa9, 0x42, 0x82, 0x7a, 0xe8, 0x8e, 0x90, 0x12, 0xd2, 0xc3, 0xb0, 0x41, 0x89,
	0x21, 0x89, 0x0d, 0xec, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xc1, 0x69, 0x42,
	0xc8, 0x00, 0x00, 0x00,
}
