// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: micro.proto

package micro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Business service

type BusinessService interface {
	Recipe(ctx context.Context, in *RecipeRequest, opts ...client.CallOption) (*RecipeResponse, error)
}

type businessService struct {
	c    client.Client
	name string
}

func NewBusinessService(name string, c client.Client) BusinessService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "business"
	}
	return &businessService{
		c:    c,
		name: name,
	}
}

func (c *businessService) Recipe(ctx context.Context, in *RecipeRequest, opts ...client.CallOption) (*RecipeResponse, error) {
	req := c.c.NewRequest(c.name, "Business.Recipe", in)
	out := new(RecipeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Business service

type BusinessHandler interface {
	Recipe(context.Context, *RecipeRequest, *RecipeResponse) error
}

func RegisterBusinessHandler(s server.Server, hdlr BusinessHandler, opts ...server.HandlerOption) error {
	type business interface {
		Recipe(ctx context.Context, in *RecipeRequest, out *RecipeResponse) error
	}
	type Business struct {
		business
	}
	h := &businessHandler{hdlr}
	return s.Handle(s.NewHandler(&Business{h}, opts...))
}

type businessHandler struct {
	BusinessHandler
}

func (h *businessHandler) Recipe(ctx context.Context, in *RecipeRequest, out *RecipeResponse) error {
	return h.BusinessHandler.Recipe(ctx, in, out)
}
