// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro.proto

package micro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecipeRequest struct {
	RequestJSON          string   `protobuf:"bytes,1,opt,name=requestJSON,proto3" json:"requestJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeRequest) Reset()         { *m = RecipeRequest{} }
func (m *RecipeRequest) String() string { return proto.CompactTextString(m) }
func (*RecipeRequest) ProtoMessage()    {}
func (*RecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{0}
}

func (m *RecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeRequest.Unmarshal(m, b)
}
func (m *RecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeRequest.Marshal(b, m, deterministic)
}
func (m *RecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeRequest.Merge(m, src)
}
func (m *RecipeRequest) XXX_Size() int {
	return xxx_messageInfo_RecipeRequest.Size(m)
}
func (m *RecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeRequest proto.InternalMessageInfo

func (m *RecipeRequest) GetRequestJSON() string {
	if m != nil {
		return m.RequestJSON
	}
	return ""
}

type RecipeResponse struct {
	ResponseJSON         string   `protobuf:"bytes,1,opt,name=responseJSON,proto3" json:"responseJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeResponse) Reset()         { *m = RecipeResponse{} }
func (m *RecipeResponse) String() string { return proto.CompactTextString(m) }
func (*RecipeResponse) ProtoMessage()    {}
func (*RecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{1}
}

func (m *RecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeResponse.Unmarshal(m, b)
}
func (m *RecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeResponse.Marshal(b, m, deterministic)
}
func (m *RecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeResponse.Merge(m, src)
}
func (m *RecipeResponse) XXX_Size() int {
	return xxx_messageInfo_RecipeResponse.Size(m)
}
func (m *RecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeResponse proto.InternalMessageInfo

func (m *RecipeResponse) GetResponseJSON() string {
	if m != nil {
		return m.ResponseJSON
	}
	return ""
}

func init() {
	proto.RegisterType((*RecipeRequest)(nil), "RecipeRequest")
	proto.RegisterType((*RecipeResponse)(nil), "RecipeResponse")
}

func init() { proto.RegisterFile("micro.proto", fileDescriptor_0147923bbc6a29d9) }

var fileDescriptor_0147923bbc6a29d9 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4c, 0x2e,
	0xca, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe4, 0xe2, 0x0d, 0x4a, 0x4d, 0xce, 0x2c,
	0x48, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0x2e, 0x82, 0x30, 0xbd,
	0x82, 0xfd, 0xfd, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x94, 0x4c, 0xb8, 0xf8,
	0x60, 0x5a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x94, 0xb8, 0x78, 0x8a, 0xa0, 0x6c, 0x24,
	0x4d, 0x28, 0x62, 0x46, 0xe6, 0x5c, 0x1c, 0x4e, 0xa5, 0xc5, 0x99, 0x79, 0xa9, 0xc5, 0xc5, 0x42,
	0xda, 0x5c, 0x6c, 0x10, 0x13, 0x84, 0xf8, 0xf4, 0x50, 0x6c, 0x97, 0xe2, 0xd7, 0x43, 0x35, 0x5a,
	0x89, 0x21, 0x89, 0x0d, 0xec, 0x50, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xef, 0xb3,
	0xee, 0xb7, 0x00, 0x00, 0x00,
}
